"use strict";

const { expect } = require("chai");
const { createDoc, createDocV4, expectToThrow, shouldBeSame, captureLogs } = require("../utils.js");
const { xml2str, traits, uniq } = require("../../doc-utils.js");
const fixDocPrCorruption = require("../../modules/fix-doc-pr-corruption.js");

describe("Module attachment", function () {
  it.only("should not allow to attach the same module twice", async function () {
    const module = {
      name: "TestModule",
      requiredAPIVersion: "3.0.0",
      render: function (part) {
        return part.value;
      },
    };

    const doc1 = createDoc("loop-valid.docx");
    doc1.attachModule(module);

    const doc2 = createDoc("tag-example.docx");

    let errMessage = null;
    try {
      doc2.attachModule(module);
    } catch (e) {
      errMessage = e.message;
    }

    expect(errMessage).to.equal(
      'Cannot attach a module that was already attached : "TestModule". The most likely cause is that you are instantiating the module at the root level, and using it for multiple instances of Docxtemplater'
    );
  });
});
